M48
; DRILL file {KiCad 7.0.9} date 
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-06T15:59:14+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X200.885Y-99.125
X205.735Y-99.125
T2
X200.585Y-96.095
X206.035Y-96.095
T3
X165.0Y-95.0
X186.0Y-146.0
X252.0Y-143.0
X253.0Y-97.0
T0
M30
