M48
; DRILL file {KiCad 7.0.9} date 
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-04T13:54:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X178.7Y-51.375
X183.55Y-51.375
T2
X178.4Y-48.345
X183.85Y-48.345
T0
M30
